apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
spec:
  storageClassName: manual
  capacity:
    storage: 4G
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/lib/mongodb/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4G
